version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: "npm run dev"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./:/usr/src/app
